feat: lazy load
tjallingt/react-youtube pull request #308
Opened 2021-08-18 04:34 UTC by Foo-x

Refs #234

![image](https://user-images.githubusercontent.com/24248467/129836946-377258b2-d768-4225-833d-3d13d9d524d1.png)
![lazy-load](https://user-images.githubusercontent.com/24248467/129836977-52a37969-5eea-4904-be6f-ce02493d1ae3.gif)

I wish it would be released if merged.

2021-08-18 21:14 UTC, ruisaraiva19 requested changes

2021-08-18 21:14 UTC, ruisaraiva19 commented on src/YouTube.js
> +  loading: PropTypes.string,
This prop type can be more specific to only accept 'lazy', 'eager', and 'auto'.

2021-08-18 21:14 UTC, ruisaraiva19 commented on src/YouTube.js
> +  loading: '',
With the comment above, the default value can be 'auto'.

2021-08-19 01:09 UTC, Foo-x commented
Thank you for your review!
Since `auto` is the Chromium specific value, I think that the default value should be `null` to let the browser decide.
It will be `auto` on Chromium and `eager` on the others.
What do you think?

I've pushed with the above.

2021-08-19 06:22 UTC, ruisaraiva19 approved these changes

2021-08-19 06:23 UTC, merged